services:
  - type: web
    name: lavalust-products
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_DRIVER
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_SSL_CA
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_TOKEN_KEY
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: CORS_ALLOWED_ORIGIN
        sync: false
      - key: DB_CHARSET
        value: utf8mb4
